// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAphAbAONFL1GEwBp5NxmvNeCUENG_UWYA',
    appId: '1:946292666203:web:a4bdeb53c9917b8310b47e',
    messagingSenderId: '946292666203',
    projectId: 'healthsteady-f1a92',
    authDomain: 'healthsteady-f1a92.firebaseapp.com',
    storageBucket: 'healthsteady-f1a92.appspot.com',
    measurementId: 'G-ZMBQX1KFM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiA1KSzZB6qvWqAqgbIVpi-C5Ks7EEfZU',
    appId: '1:946292666203:android:073b0d37b340f79d10b47e',
    messagingSenderId: '946292666203',
    projectId: 'healthsteady-f1a92',
    storageBucket: 'healthsteady-f1a92.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyyvjyzVsbTGljaclORoaxFavhxxOPtMs',
    appId: '1:946292666203:ios:8f1e033879ba2e3710b47e',
    messagingSenderId: '946292666203',
    projectId: 'healthsteady-f1a92',
    storageBucket: 'healthsteady-f1a92.appspot.com',
    iosBundleId: 'com.example.healthsteady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyyvjyzVsbTGljaclORoaxFavhxxOPtMs',
    appId: '1:946292666203:ios:c4ca960ffd018ddf10b47e',
    messagingSenderId: '946292666203',
    projectId: 'healthsteady-f1a92',
    storageBucket: 'healthsteady-f1a92.appspot.com',
    iosBundleId: 'com.example.healthsteady.RunnerTests',
  );
}
